export default {
  info    : {
    static   : {
      gridList: [12],
    },
    cssObj   : {
      self: {
        css: {
          minHeight: '450px',
        },
      },
    },
    tplCssObj: {
      self: {
        css: {
          minHeight   : '450px',
          marginTop   : '-158px !important',
          marginBottom: '-158px !important',
        },
      },
    },
  },
  children: [
    {
      info    : {
        name     : 'module-list',
        cName    : '列表',
        className: 'ABt',
        sequence : 0,
        lock     : {},
        cssObj   : {
          self      : {
            class: '',
            css  : {
              left        : '0px',
              top         : '0px',
              width       : '100%',
              position    : 'relative !important',
              marginBottom: '0px',
            },
          },
          inner     : {
            class   : '.inner-group',
            css     : {
              border: '1px solid rgba(226,226,226,1)',
            },
            hoverCss: {},
          },
          innerGap  : {
            class: '.inner-gap',
            css  : {
              width  : '100%',
              padding: '18px',
            },
          },
          innerGroup: {
            class   : '.inner-group',
            css     : {
              height: '189px',
            },
            hoverCss: {},
          },
        },
        static   : {
          direction  : 'multi-row',
          columnCount: 1,
          dataOrigin : 0,
          dataList   : [
            {
              src__Ong     : '',
              link__Ong    : '',
              text__u7E    : '周末双休',
              link__u7E    : '',
              icon__u7E    : '',
              text__9B4    : '五险一金',
              link__9B4    : '',
              icon__9B4    : '',
              text__dkg    : '查看详情',
              link__dkg    : '',
              icon__dkg    : '',
              textarea__nrW: '  5职位正在招聘',
              link__nrW    : '',
              icon__nrW    : 'icl-idcard',
              textarea__PgS: ' 50-100人',
              link__PgS    : '',
              icon__PgS    : 'icl-team',
              textarea__YbK: ' 广州',
              link__YbK    : '',
              icon__YbK    : 'icl-location',
              text__RMn    : '请输入公司描述',
              link__RMn    : '',
              icon__RMn    : '',
              text__Abw    : '公司名称',
              link__Abw    : '',
              icon__Abw    : '',
              src__fct     : 'usr/6QN4pQxWbP/5c18668b49b6c.jpg',
              link__fct    : '',
            },
            {
              src__Ong     : '',
              link__Ong    : '',
              text__u7E    : '周末双休',
              link__u7E    : '',
              icon__u7E    : '',
              text__9B4    : '五险一金',
              link__9B4    : '',
              icon__9B4    : '',
              text__dkg    : '查看详情',
              link__dkg    : '',
              icon__dkg    : '',
              textarea__nrW: '  5职位正在招聘',
              link__nrW    : '',
              icon__nrW    : 'icl-idcard',
              textarea__PgS: ' 50-100人',
              link__PgS    : '',
              icon__PgS    : 'icl-team',
              textarea__YbK: ' 广州',
              link__YbK    : '',
              icon__YbK    : 'icl-location',
              text__RMn    : '请输入公司描述',
              link__RMn    : '',
              icon__RMn    : '',
              text__Abw    : '公司名称',
              link__Abw    : '',
              icon__Abw    : '',
              src__fct     : 'usr/6QN4pQxWbP/5c18668b49b6c.jpg',
              link__fct    : '',
            },
          ],
          swiperInit : {
            autoplay      : {
              delay: 2000,
            },
            loop          : false,
            speed         : 400,
            slidesPerView : 1,
            effect        : 'slide',
            wrapperClass  : 'wrapper',
            slideClass    : 'inner-gap',
            direction     : 'horizontal',
            allowTouchMove: false,
            observer      : true,
            observeParents: true,
          },
        },
      },
      children: [
        {
          info: {
            name     : 'module-xz',
            cName    : '形状',
            lock     : {},
            static   : {
              svg    : '<svg viewBox="9.039993286132812 19.052000045776367 186 103" preserveAspectRatio="ASPECTRATIO">\n            <defs>\n              <image id="img-CLASSNAME" xlink:href="SRC" preserveAspectRatio="xMidYMid slice" x="9.039993286132812" y="19.052000045776367" width="100%" height="100%"/>\n              <path id="path-CLASSNAME" preserveAspectRatio="xMidYMid slice" d="M195.04 19.052v103h-186v-103h186z"></path>\n              <clipPath id="cp-CLASSNAME">\n                <use xlink:href="#path-CLASSNAME"/>\n              </clipPath>\n            </defs>\n            <use xlink:href="#WITCHONE-CLASSNAME" clip-path="url(#cp-CLASSNAME)" />\n\t\t\t\t\t</svg>',
              ratio  : 0,
              witch  : 0,
              src    : '',
              link   : '',
              d__src : 'src__Ong',
              d__link: 'link__Ong',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : 'initial',
                  width : '100%',
                  height: '57px',
                  bottom: '0px',
                },
              },
              inner: {
                class        : '.inner',
                css          : {
                  fill: 'rgba(249,249,249,1)',
                },
                hoverCss     : {},
                groupHoverCss: {},
              },
            },
            className: 'Ong',
            moduleCss: '3',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '周末双休',
              link   : '',
              icon   : '',
              d__text: 'text__u7E',
              d__link: 'link__u7E',
              d__icon: 'icon__u7E',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '20px',
                  top   : '142px',
                  width : '8%',
                  height: '34px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color          : 'rgba(61,61,61,1)',
                  border         : '1px solid rgba(224,224,224,1)',
                  transition     : 'all 0.2s 0s ease',
                  borderRadius   : '40px',
                  fontSize       : '12px',
                  backgroundColor: 'rgba(255,255,255,1)',
                },
              },
            },
            lock     : {},
            className: 'u7E',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '五险一金',
              link   : '',
              icon   : '',
              d__text: 'text__9B4',
              d__link: 'link__9B4',
              d__icon: 'icon__9B4',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '110px',
                  top   : '142px',
                  width : '8%',
                  height: '34px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color          : 'rgba(61,61,61,1)',
                  border         : '1px solid rgba(224,224,224,1)',
                  transition     : 'all 0.2s 0s ease',
                  borderRadius   : '40px',
                  fontSize       : '12px',
                  backgroundColor: 'rgba(255,255,255,1)',
                },
              },
            },
            lock     : {},
            className: '9B4',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '查看详情',
              link   : '',
              icon   : '',
              d__text: 'text__dkg',
              d__link: 'link__dkg',
              d__icon: 'icon__dkg',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '87%',
                  top   : '58px',
                  width : '11%',
                  height: '40px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color       : 'rgba(61,61,61,1)',
                  border      : '1px solid rgba(224,224,224,1)',
                  transition  : 'all 0.2s 0s ease',
                  borderRadius: '40px',
                  fontSize    : '12px',
                },
              },
            },
            lock     : {},
            className: 'dkg',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              link       : '',
              icon       : 'icl-idcard',
              d__link    : 'link__nrW',
              d__icon    : 'icon__nrW',
              order      : 0,
              script     : '',
              textarea   : '  5职位正在招聘',
              d__textarea: 'textarea__nrW',
              rows       : 2,
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '32%',
                  top   : '81px',
                  width : '15%',
                  height: '25px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(101,101,101,1)',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '16px',
                },
              },
            },
            lock     : {},
            className: 'nrW',
            moduleCss: '2',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              link       : '',
              icon       : 'icl-team',
              d__link    : 'link__PgS',
              d__icon    : 'icon__PgS',
              order      : 0,
              script     : '',
              textarea   : ' 50-100人',
              d__textarea: 'textarea__PgS',
              rows       : 2,
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '20%',
                  top   : '79px',
                  width : '12%',
                  height: '25px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(101,101,101,1)',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '16px',
                },
              },
            },
            lock     : {},
            className: 'PgS',
            moduleCss: '2',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              link       : '',
              icon       : 'icl-location',
              d__link    : 'link__YbK',
              d__icon    : 'icon__YbK',
              order      : 0,
              script     : '',
              textarea   : ' 广州',
              d__textarea: 'textarea__YbK',
              rows       : 2,
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '12%',
                  top   : '79px',
                  width : '8%',
                  height: '25px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(101,101,101,1)',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '16px',
                },
              },
            },
            lock     : {},
            className: 'YbK',
            moduleCss: '2',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '请输入公司描述',
              link   : '',
              icon   : '',
              d__text: 'text__RMn',
              d__link: 'link__RMn',
              d__icon: 'icon__RMn',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '22%',
                  top   : '34px',
                  width : '24%',
                  height: '31px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(138,138,138,1)',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '14px',
                },
              },
            },
            lock     : {},
            className: 'RMn',
            moduleCss: '2',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '公司名称',
              link   : '',
              icon   : '',
              d__text: 'text__Abw',
              d__link: 'link__Abw',
              d__icon: 'icon__Abw',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '12%',
                  top   : '32px',
                  width : '10%',
                  height: '31px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(85,85,85,1)',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '20px',
                },
              },
            },
            lock     : {},
            className: 'Abw',
            moduleCss: '2',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-tp',
            cName    : '图片',
            lock     : {},
            static   : {
              src    : 'usr/6QN4pQxWbP/5c18668b49b6c.jpg',
              link   : '',
              d__src : 'src__fct',
              d__link: 'link__fct',
              script : '',
            },
            cssObj   : {
              self : {
                class   : '',
                css     : {
                  left  : '3%',
                  top   : '29px',
                  width : '7.6%',
                  height: '75px',
                },
                hoverCss: {},
              },
              inner: {
                class        : [
                  '.inner',
                  '.inner:before',
                  '.inner img',
                ],
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  transition: 'all 0.2s 0s ease',
                },
              },
            },
            className: 'fct',
            moduleCss: '1',
            sequence : 0,
          },
        },
      ],
    },
  ],
  tab     : [],
}
