export default {
  info    : {
    static   : {
      gridList: [12],
    },
    cssObj   : {
      self: {
        css: {
          minHeight: '560px',
        },
      },
    },
    tplCssObj: {
      self: {
        css: {
          minHeight   : '560px',
          marginTop   : '-169px !important',
          marginBottom: '-169px !important',
        },
      },
    },
  },
  children: [
    {
      info    : {
        name     : 'module-group',
        cName    : '分组',
        className: 'uV07',
        sequence : 0,
        lock     : {},
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : '0%',
              top   : '20px',
              width : '100%',
              height: '62px',
            },
          },
          inner: {
            class   : '.inner-group',
            css     : {},
            hoverCss: {},
          },
        },
      },
      children: [
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '热招岗位',
              link   : '',
              icon   : '',
              d__text: 'text__uqty',
              d__link: 'link__uqty',
              d__icon: 'icon__uqty',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '0px',
                  width : '100%',
                  height: '35px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(48,48,48,1)',
                  fontWeight    : 'bold',
                  fontSize      : '20px',
                  textAlign     : 'center',
                  justifyContent: 'center',
                },
              },
            },
            lock     : {},
            className: 'uqty',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '汇聚专业猎头，面向精英人才',
              link   : '',
              icon   : '',
              d__text: 'text__r0lf',
              d__link: 'link__r0lf',
              d__icon: 'icon__r0lf',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '35px',
                  width : '100%',
                  height: '27px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(105,105,105,1)',
                  fontWeight    : 'normal',
                  fontSize      : '16px',
                  textAlign     : 'center',
                  justifyContent: 'center',
                },
              },
            },
            lock     : {},
            className: 'r0lf',
            moduleCss: '1',
            sequence : 0,
          },
        },
      ],
    },
    {
      info    : {
        name     : 'module-list',
        cName    : '列表',
        sequence : 0,
        lock     : {},
        cssObj   : {
          self      : {
            class: '',
            css  : {
              left        : '0%',
              top         : '104px',
              width       : '100%',
              position    : 'relative !important',
              marginBottom: '104px',
            },
          },
          inner     : {
            class   : '.inner-group',
            hoverCss: {},
            css     : {
              borderTop   : '0px solid rgba(0,0,0,1)',
              borderRight : '0px solid rgba(0,0,0,1)',
              borderBottom: '1px solid rgba(233,233,233,1)',
              borderLeft  : '0px solid rgba(0,0,0,1)',
            },
          },
          innerGap  : {
            class: '.inner-gap',
            css  : {
              width  : '100%',
              padding: '0px',
            },
          },
          innerGroup: {
            class   : '.inner-group',
            css     : {
              height: '143.5px',
            },
            hoverCss: {},
          },
        },
        className: 'gg2g',
        moduleCss: '1',
        static   : {
          direction  : 'multi-row',
          columnCount: 1,
          dataOrigin : 0,
          dataList   : [
            {
              text__ys4w    : '元/月',
              link__ys4w    : '',
              icon__ys4w    : '',
              text__vnwq    : '5000-7500',
              link__vnwq    : '',
              icon__vnwq    : '',
              textarea__rqG2: '五险一金  周末双休  周末双休  周末双休',
              link__rqG2    : '',
              icon__rqG2    : '',
              text__xzk7    : '广州 | 急聘酒店经理',
              link__xzk7    : '',
              icon__xzk7    : '',
              text__4urH    : '广东股份有限公司',
              link__4urH    : '',
              icon__4urH    : '',
              textarea__vMYF: '经理   |   高中毕业   |   不限',
              link__vMYF    : '',
              icon__vMYF    : '',
              text__pAUn    : '申请',
              link__pAUn    : '',
              icon__pAUn    : '',
            },
            {
              text__ys4w    : '元/月',
              link__ys4w    : '',
              icon__ys4w    : '',
              text__vnwq    : '5000-7500',
              link__vnwq    : '',
              icon__vnwq    : '',
              textarea__rqG2: '五险一金  周末双休  周末双休  周末双休',
              link__rqG2    : '',
              icon__rqG2    : '',
              text__xzk7    : '广州 | 急聘酒店经理',
              link__xzk7    : '',
              icon__xzk7    : '',
              text__4urH    : '广东股份有限公司',
              link__4urH    : '',
              icon__4urH    : '',
              textarea__vMYF: '经理   |   高中毕业   |   不限',
              link__vMYF    : '',
              icon__vMYF    : '',
              text__pAUn    : '申请',
              link__pAUn    : '',
              icon__pAUn    : '',
            },
            {
              text__ys4w    : '元/月',
              link__ys4w    : '',
              icon__ys4w    : '',
              text__vnwq    : '5000-7500',
              link__vnwq    : '',
              icon__vnwq    : '',
              textarea__rqG2: '五险一金  周末双休  周末双休  周末双休',
              link__rqG2    : '',
              icon__rqG2    : '',
              text__xzk7    : '广州 | 急聘酒店经理',
              link__xzk7    : '',
              icon__xzk7    : '',
              text__4urH    : '广东股份有限公司',
              link__4urH    : '',
              icon__4urH    : '',
              textarea__vMYF: '经理   |   高中毕业   |   不限',
              link__vMYF    : '',
              icon__vMYF    : '',
              text__pAUn    : '申请',
              link__pAUn    : '',
              icon__pAUn    : '',
            },
          ],
          swiperInit : {
            autoplay      : {
              delay: 2000,
            },
            loop          : false,
            speed         : 400,
            slidesPerView : 1,
            effect        : 'slide',
            wrapperClass  : 'wrapper',
            slideClass    : 'inner-gap',
            direction     : 'horizontal',
            allowTouchMove: false,
            observer      : true,
            observeParents: true,
          },
        },
      },
      children: [
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '元/月',
              link   : '',
              icon   : '',
              d__text: 'text__ys4w',
              d__link: 'link__ys4w',
              d__icon: 'icon__ys4w',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '9.581%',
                  top   : '60.024px',
                  width : '12.623%',
                  height: '23px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(253,103,53,1)',
                  fontWeight    : 'normal',
                  fontSize      : '12px',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                },
              },
            },
            lock     : {},
            className: 'ys4w',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '5000-7500',
              link   : '',
              icon   : '',
              d__text: 'text__vnwq',
              d__link: 'link__vnwq',
              d__icon: 'icon__vnwq',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '54px',
                  width : '9.616%',
                  height: '32px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(253,103,53,1)',
                  fontWeight    : 'bold',
                  fontSize      : '18px',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                },
              },
            },
            lock     : {},
            className: 'vnwq',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              link       : '',
              icon       : '',
              d__link    : 'link__rqG2',
              d__icon    : 'icon__rqG2',
              order      : 0,
              script     : '',
              textarea   : '五险一金  周末双休  周末双休  周末双休',
              d__textarea: 'textarea__rqG2',
              rows       : 2,
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '89.5px',
                  width : '40%',
                  height: '27px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(111,149,186,1)',
                  fontWeight    : 'normal',
                  fontSize      : '12px',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                },
              },
            },
            lock     : {},
            className: 'rqG2',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '广州 | 急聘酒店经理',
              link   : '',
              icon   : '',
              d__text: 'text__xzk7',
              d__link: 'link__xzk7',
              d__icon: 'icon__xzk7',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0%',
                  top   : '21px',
                  width : '100%',
                  height: '27px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(48,48,48,1)',
                  fontWeight    : 'bold',
                  fontSize      : '20px',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                },
              },
            },
            lock     : {},
            className: 'xzk7',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              link   : '',
              icon   : '',
              d__link: 'link__4urH',
              d__icon: 'icon__4urH',
              order  : 0,
              script : '',
              text   : '广东股份有限公司',
              d__text: 'text__4urH',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : 'calc(50% - 14.5%)',
                  top   : '56.024px',
                  width : '29%',
                  height: '27px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(54,54,54,1)',
                  fontWeight    : 'normal',
                  fontSize      : '16px',
                  textAlign     : 'center',
                  justifyContent: 'center',
                },
              },
            },
            lock     : {},
            className: '4urH',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              link       : '',
              icon       : '',
              d__link    : 'link__vMYF',
              d__icon    : 'icon__vMYF',
              order      : 0,
              script     : '',
              textarea   : '经理   |   高中毕业   |   不限',
              d__textarea: 'textarea__vMYF',
              rows       : 2,
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : 'calc(50% - 14.5%)',
                  top   : '89.5px',
                  width : '29%',
                  height: '27px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(147,147,147,1)',
                  fontWeight    : 'normal',
                  fontSize      : '12px',
                  textAlign     : 'center',
                  justifyContent: 'center',
                },
              },
            },
            lock     : {},
            className: 'vMYF',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '申请',
              link   : '',
              icon   : '',
              d__text: 'text__pAUn',
              d__link: 'link__pAUn',
              d__icon: 'icon__pAUn',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : 'calc(100% - 11.997%)',
                  top   : '75px',
                  width : '11.997%',
                  height: '34px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color          : 'rgba(255,255,255,1)',
                  backgroundColor: 'rgba(255,101,55,1)',
                  borderRadius   : '6px',
                  textAlign      : 'center',
                  justifyContent : 'center',
                },
              },
            },
            lock     : {},
            className: 'pAUn',
            moduleCss: '2',
            sequence : 0,
          },
        },
      ],
    },
  ],
  tab     : [],
}
