export default {
  info    : {
    name     : 'module-group',
    cName    : '分组',
    className: '92r',
    sequence : 0,
    lock     : {},
    cssObj   : {
      self : {
        class: '',
        css  : {
          left  : '0%',
          top   : '15px',
          width : '100%',
          height: '50px',
        },
      },
      inner: {
        class   : '.inner-group',
        css     : {
          borderTop   : '4px solid rgba(247,50,93,1)',
          borderRight : '0px solid rgba(247,50,93,1)',
          borderBottom: '1px solid rgba(229,229,229,1)',
          borderLeft  : '0px solid rgba(247,50,93,1)',
        },
        hoverCss: {},
      },
    },
  },
  children: [
    {
      info: {
        name     : 'module-an',
        cName    : '按钮',
        static   : {
          text   : '第一主标题',
          link   : '',
          icon   : '',
          d__text: 'text__n9c0',
          d__link: 'link__n9c0',
          d__icon: 'icon__n9c0',
          order  : 0,
          script : '',
        },
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : '184.812px',
              top   : '14.128px',
              width : '138px',
              height: '17px',
            },
          },
          inner: {
            class        : '.inner',
            hoverCss     : {},
            groupHoverCss: {},
            css          : {
              color         : 'rgba(247,50,93,1)',
              fontWeight    : 'bold',
              fontSize      : '18px',
              textAlign     : 'left',
              justifyContent: 'flex-start',
              alignItems    : 'center',
              fontFamily    : '黑体',
              borderTop     : '0px solid rgba(247,50,93,1)',
              borderRight   : '0px solid rgba(247,50,93,1)',
              borderBottom  : '0px solid rgba(247,50,93,1)',
              borderLeft    : '1px solid rgba(247,50,93,1)',
              textIndent    : '8px',
            },
          },
        },
        lock     : {
          d: false,
          r: false,
        },
        className: 'n9c0',
        moduleCss: '2',
        sequence : 0,
      },
    },
    {
      info: {
        name     : 'module-an',
        cName    : '按钮',
        static   : {
          text   : 'PRODUCT STUDY',
          link   : '',
          icon   : '',
          d__text: 'text__nxVx',
          d__link: 'link__nxVx',
          d__icon: 'icon__nxVx',
          order  : 0,
          script : '',
        },
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : '41.996px',
              top   : '27.907%',
              width : '138px',
              height: '20px',
            },
          },
          inner: {
            class        : '.inner',
            hoverCss     : {},
            groupHoverCss: {},
            css          : {
              color         : 'rgba(247,50,93,1)',
              fontWeight    : 'bold',
              fontSize      : '14px',
              textAlign     : 'left',
              justifyContent: 'flex-start',
              alignItems    : 'center',
              fontFamily    : '微软雅黑',
              textIndent    : '8px',
            },
          },
        },
        lock     : {
          d: false,
          r: false,
        },
        className: 'nxVx',
        moduleCss: '2',
        sequence : 0,
      },
    },
    {
      info: {
        name     : 'module-an',
        cName    : '按钮',
        static   : {
          text   : '',
          link   : '',
          icon   : 'icl-gift',
          d__text: 'text__FG7z',
          d__link: 'link__FG7z',
          d__icon: 'icon__FG7z',
          order  : 0,
          script : '',
        },
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : '14.004px',
              top   : 'calc(50% - 13px)',
              width : '24.972px',
              height: '26px',
            },
          },
          inner: {
            class        : '.inner',
            hoverCss     : {},
            groupHoverCss: {},
            css          : {
              color         : 'rgba(247,50,93,1)',
              fontWeight    : 'bold',
              fontSize      : '23px',
              textAlign     : 'left',
              justifyContent: 'flex-start',
              alignItems    : 'center',
              fontFamily    : '微软雅黑',
              textIndent    : '0px',
            },
          },
        },
        lock     : {
          d: false,
          r: false,
        },
        className: 'FG7z',
        moduleCss: '2',
        sequence : 0,
      },
    },
    {
      info: {
        name     : 'module-an',
        cName    : '按钮',
        static   : {
          text   : 'MORE+',
          link   : '',
          icon   : '',
          d__text: 'text__ATxY',
          d__link: 'link__ATxY',
          d__icon: 'icon__ATxY',
          order  : 0,
          script : '',
        },
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : 'calc(100% - 60.996px)',
              top   : '22.222%',
              width : '60.996px',
              height: '24px',
            },
          },
          inner: {
            class        : '.inner',
            hoverCss     : {},
            groupHoverCss: {},
            css          : {
              color         : 'rgba(204,204,204,1)',
              fontWeight    : 'normal',
              fontSize      : '12px',
              textAlign     : 'left',
              justifyContent: 'flex-start',
              alignItems    : 'center',
              fontFamily    : '微软雅黑',
              textIndent    : '0px',
            },
          },
        },
        lock     : {
          d: false,
          r: false,
        },
        className: 'ATxY',
        moduleCss: '2',
        sequence : 0,
      },
    },
  ],
}
