export default {
  info    : {
    static   : {
      gridList: [12],
    },
    cssObj   : {
      self: {
        css: {
          minHeight: '340px',
        },
      },
    },
  },
  children: [
    {
      info    : {
        name     : 'module-list',
        cName    : '列表',
        className: 'oYg',
        sequence : 0,
        lock     : {},
        cssObj   : {
          self      : {
            class: '',
            css  : {
              left        : '0px',
              top         : '0px',
              width       : '100%',
              position    : 'relative !important',
              marginBottom: '0px',
            },
          },
          inner     : {
            class   : '.inner-group',
            css     : {
              border: '1px solid rgba(228,228,228,1)',
            },
            hoverCss: {},
          },
          innerGap  : {
            class: '.inner-gap',
            css  : {
              width  : '50%',
              padding: '26px',
            },
          },
          innerGroup: {
            class   : '.inner-group',
            css     : {
              height: '117px',
            },
            hoverCss: {},
          },
        },
        static   : {
          direction  : 'multi-row',
          columnCount: 2,
          dataOrigin : 0,
          dataList   : [
            {
              text__se4    : '产品经理',
              link__se4    : '',
              icon__se4    : '',
              text__agG    : '经验1-3年 / 本科',
              link__agG    : '',
              icon__agG    : '',
              textarea__1NL: '五险一金  |  周末双休  |  周末双休  |  周末双休',
              link__1NL    : '',
              icon__1NL    : '',
              text__KRr    : '5k-10k',
              link__KRr    : '',
              icon__KRr    : '',
            },
            {
              text__se4    : '产品经理',
              link__se4    : '',
              icon__se4    : '',
              text__agG    : '经验1-3年 / 本科',
              link__agG    : '',
              icon__agG    : '',
              textarea__1NL: '五险一金  |  周末双休  |  周末双休  |  周末双休',
              link__1NL    : '',
              icon__1NL    : '',
              text__KRr    : '5k-10k',
              link__KRr    : '',
              icon__KRr    : '',
            },
            {
              text__se4    : '产品经理',
              link__se4    : '',
              icon__se4    : '',
              text__agG    : '经验1-3年 / 本科',
              link__agG    : '',
              icon__agG    : '',
              textarea__1NL: '五险一金  |  周末双休  |  周末双休  |  周末双休',
              link__1NL    : '',
              icon__1NL    : '',
              text__KRr    : '5k-10k',
              link__KRr    : '',
              icon__KRr    : '',
            },
            {
              text__se4    : '产品经理',
              link__se4    : '',
              icon__se4    : '',
              text__agG    : '经验1-3年 / 本科',
              link__agG    : '',
              icon__agG    : '',
              textarea__1NL: '五险一金  |  周末双休  |  周末双休  |  周末双休',
              link__1NL    : '',
              icon__1NL    : '',
              text__KRr    : '5k-10k',
              link__KRr    : '',
              icon__KRr    : '',
            },
          ],
          swiperInit : {
            autoplay      : {
              delay: 2000,
            },
            loop          : false,
            speed         : 400,
            slidesPerView : 1,
            effect        : 'slide',
            wrapperClass  : 'wrapper',
            slideClass    : 'inner-gap',
            direction     : 'horizontal',
            allowTouchMove: false,
            observer      : true,
            observeParents: true,
          },
        },
      },
      children: [
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '产品经理',
              link   : '',
              icon   : '',
              d__text: 'text__se4',
              d__link: 'link__se4',
              d__icon: 'icon__se4',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '5%',
                  top   : '11px',
                  width : '57%',
                  height: '29px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(92,92,92,1)',
                  transition    : 'all 0.2s 0s ease',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '20px',
                },
              },
            },
            lock     : {},
            className: 'se4',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '经验1-3年 / 本科',
              link   : '',
              icon   : '',
              d__text: 'text__agG',
              d__link: 'link__agG',
              d__icon: 'icon__agG',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '5%',
                  top   : '42px',
                  width : '57%',
                  height: '22px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(92,92,92,1)',
                  transition    : 'all 0.2s 0s ease',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '14px',
                },
              },
            },
            lock     : {},
            className: 'agG',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              link       : '',
              icon       : '',
              d__link    : 'link__1NL',
              d__icon    : 'icon__1NL',
              order      : 0,
              script     : '',
              textarea   : '五险一金  |  周末双休  |  周末双休  |  周末双休',
              d__textarea: 'textarea__1NL',
              rows       : 2,
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '5%',
                  top   : '81px',
                  width : '95%',
                  height: '22px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(92,92,92,1)',
                  transition    : 'all 0.2s 0s ease',
                  textAlign     : 'left',
                  justifyContent: 'flex-start',
                  fontSize      : '13px',
                },
              },
            },
            lock     : {},
            className: '1NL',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '5k-10k',
              link   : '',
              icon   : '',
              d__text: 'text__KRr',
              d__link: 'link__KRr',
              d__icon: 'icon__KRr',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '73%',
                  top   : '20px',
                  width : '21%',
                  height: '29px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color         : 'rgba(254,101,60,1)',
                  transition    : 'all 0.2s 0s ease',
                  textAlign     : 'right',
                  justifyContent: 'flex-end',
                  fontSize      : '20px',
                },
              },
            },
            lock     : {},
            className: 'KRr',
            moduleCss: '1',
            sequence : 0,
          },
        },
      ],
    },
  ],
  tab     : [],
}
