export default {
  info    : {
    cssObj: {
      self : {},
      inner: {
        class   : '.inner-group',
        css     : {
          class: '',
          css  : {
            left  : '0px',
            top   : '0px',
            width : '115px',
            height: '141px',
          },
        },
        hoverCss: {},
      },
    },
  },
  children: [
    {
      info: {
        name     : 'module-an',
        cName    : '按钮',
        static   : {
          text   : '第一主标题',
          link   : '',
          icon   : '',
          d__text: 'text__o1np',
          d__link: 'link__o1np',
          d__icon: 'icon__o1np',
          order  : 0,
          script : '',
        },
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : '46.531px',
              top   : '33px',
              width : '41.795px',
              height: '127px',
            },
          },
          inner: {
            class        : '.inner',
            hoverCss     : {},
            groupHoverCss: {},
            css          : {
              color         : 'rgba(67,67,67,1)',
              transition    : 'all 0.2s 0s ease',
              fontSize      : '24px',
              writingMode   : 'tb-rl',
              alignItems    : 'center',
              textAlign     : 'center',
              justifyContent: 'center',
              borderTop     : '0px solid rgba(0,0,0,1)',
              borderRight   : '1px solid rgba(114,114,114,1)',
              borderBottom  : '0px solid rgba(0,0,0,1)',
              borderLeft    : '1px solid rgba(114,114,114,1)',
              lineHeight    : '1',
            },
          },
        },
        lock     : {},
        className: 'o1np',
        moduleCss: '1',
        sequence : 0,
      },
    },
    {
      info: {
        name     : 'module-an',
        cName    : '按钮',
        static   : {
          text   : '2019.01.28',
          link   : '',
          icon   : '',
          d__text: 'text__Atp8',
          d__link: 'link__Atp8',
          d__icon: 'icon__Atp8',
          order  : 0,
          script : '',
        },
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : '25.531px',
              top   : '92px',
              width : '18.283px',
              height: '68px',
            },
          },
          inner: {
            class        : '.inner',
            hoverCss     : {},
            groupHoverCss: {},
            css          : {
              color         : 'rgba(67,67,67,1)',
              transition    : 'all 0.2s 0s ease',
              fontSize      : '12px',
              writingMode   : 'tb-rl',
              alignItems    : 'center',
              textAlign     : 'center',
              justifyContent: 'center',
              lineHeight    : '1',
            },
          },
        },
        lock     : {},
        className: 'Atp8',
        moduleCss: '1',
        sequence : 0,
      },
    },
    {
      info: {
        name     : 'module-an',
        cName    : '按钮',
        static   : {
          text   : '极捷号',
          link   : '',
          icon   : '',
          d__text: 'text__dLe8',
          d__link: 'link__dLe8',
          d__icon: 'icon__dLe8',
          order  : 0,
          script : '',
        },
        cssObj   : {
          self : {
            class: '',
            css  : {
              left  : '97.531px',
              top   : '34px',
              width : '19.213px',
              height: '48px',
            },
          },
          inner: {
            class        : '.inner',
            hoverCss     : {},
            groupHoverCss: {},
            css          : {
              color          : 'rgba(255,255,255,1)',
              transition     : 'all 0.2s 0s ease',
              fontSize       : '12px',
              writingMode    : 'tb-rl',
              alignItems     : 'center',
              textAlign      : 'center',
              justifyContent : 'center',
              lineHeight     : '1',
              backgroundColor: 'rgba(216,0,0,1)',
              boxShadow      : 'inset 11px 11px 6px -10px rgba(60,0,0,1)',
            },
          },
        },
        lock     : {},
        className: 'dLe8',
        moduleCss: '1',
        sequence : 0,
      },
    },
  ],
}
