export default {
  info    : {
    static   : {
      gridList: [12],
    },
    cssObj   : {
      self: {
        css: {
          minHeight      : '410px',
          backgroundColor: 'rgba(246,246,246,1)',
        },
      },
    },
  },
  children: [
    {
      info    : {
        name     : 'module-list',
        cName    : '列表',
        className: '13v',
        sequence : 0,
        lock     : {},
        cssObj   : {
          self      : {
            class: '',
            css  : {
              left        : '0px',
              top         : '66px',
              width       : '100%',
              position    : 'relative !important',
              marginBottom: '66px',
            },
          },
          inner     : {
            class   : '.inner-group',
            css     : {
              backgroundColor: 'rgba(255,255,255,1)',
            },
            hoverCss: {},
          },
          innerGap  : {
            class: '.inner-gap',
            css  : {
              width  : '33.333%',
              padding: '18px',
            },
          },
          innerGroup: {
            class   : '.inner-group',
            css     : {
              height: '274px',
            },
            hoverCss: {},
          },
        },
        static   : {
          direction  : 'multi-row',
          columnCount: 3,
          dataOrigin : 0,
          dataList   : [
            {
              src__zUU : '',
              link__zUU: '',
              src__TLO : '',
              link__TLO: '',
              src__9QF : '',
              link__9QF: '',
              text__Sha: '公司地址',
              link__Sha: '',
              icon__Sha: '',
              text__AAZ: '请输入要描述的内容进行内容补充',
              link__AAZ: '',
              icon__AAZ: '',
              text__17k: 'Address',
              link__17k: '',
              icon__17k: '',
              text__eX1: '',
              link__eX1: '',
              icon__eX1: '',
            },
            {
              src__zUU : '',
              link__zUU: '',
              src__TLO : '',
              link__TLO: '',
              src__9QF : '',
              link__9QF: '',
              text__Sha: '公司地址',
              link__Sha: '',
              icon__Sha: '',
              text__AAZ: '请输入要描述的内容进行内容补充',
              link__AAZ: '',
              icon__AAZ: '',
              text__17k: 'Address',
              link__17k: '',
              icon__17k: '',
              text__eX1: '',
              link__eX1: '',
              icon__eX1: '',
            },
            {
              src__zUU : '',
              link__zUU: '',
              src__TLO : '',
              link__TLO: '',
              src__9QF : '',
              link__9QF: '',
              text__Sha: '公司地址',
              link__Sha: '',
              icon__Sha: '',
              text__AAZ: '请输入要描述的内容进行内容补充',
              link__AAZ: '',
              icon__AAZ: '',
              text__17k: 'Address',
              link__17k: '',
              icon__17k: '',
              text__eX1: '',
              link__eX1: '',
              icon__eX1: '',
            },
          ],
          swiperInit : {
            autoplay      : {
              delay: 2000,
            },
            loop          : false,
            speed         : 400,
            slidesPerView : 1,
            effect        : 'slide',
            wrapperClass  : 'wrapper',
            slideClass    : 'inner-gap',
            direction     : 'horizontal',
            allowTouchMove: false,
            observer      : true,
            observeParents: true,
          },
        },
      },
      children: [
        {
          info: {
            name     : 'module-xz',
            cName    : '形状',
            lock     : {},
            static   : {
              svg    : '<svg viewBox="9.039993286132812 19.052000045776367 186 103" preserveAspectRatio="ASPECTRATIO">\n            <defs>\n              <image id="img-CLASSNAME" xlink:href="SRC" preserveAspectRatio="xMidYMid slice" x="9.039993286132812" y="19.052000045776367" width="100%" height="100%"/>\n              <path id="path-CLASSNAME" preserveAspectRatio="xMidYMid slice" d="M195.04 19.052v103h-186v-103h186z"></path>\n              <clipPath id="cp-CLASSNAME">\n                <use xlink:href="#path-CLASSNAME"/>\n              </clipPath>\n            </defs>\n            <use xlink:href="#WITCHONE-CLASSNAME" clip-path="url(#cp-CLASSNAME)" />\n\t\t\t\t\t</svg>',
              ratio  : 0,
              witch  : 0,
              src    : '',
              link   : '',
              d__src : 'src__zUU',
              d__link: 'link__zUU',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '241px',
                  width : '37%',
                  height: '27px',
                },
              },
              inner: {
                class        : '.inner',
                css          : {
                  fill     : 'rgba(255,190,199,0.58)',
                  transform: 'skew(0deg,0deg) rotateX(0deg) rotateY(0deg) rotateZ(175deg)',
                  boxShadow: '1px -9px 15px 1px rgba(166,163,163,0.5)',
                },
                hoverCss     : {},
                groupHoverCss: {},
              },
            },
            className: 'zUU',
            moduleCss: '3',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-xz',
            cName    : '形状',
            lock     : {},
            static   : {
              svg    : '<svg viewBox="9.039993286132812 19.052000045776367 186 103" preserveAspectRatio="ASPECTRATIO">\n            <defs>\n              <image id="img-CLASSNAME" xlink:href="SRC" preserveAspectRatio="xMidYMid slice" x="9.039993286132812" y="19.052000045776367" width="100%" height="100%"/>\n              <path id="path-CLASSNAME" preserveAspectRatio="xMidYMid slice" d="M195.04 19.052v103h-186v-103h186z"></path>\n              <clipPath id="cp-CLASSNAME">\n                <use xlink:href="#path-CLASSNAME"/>\n              </clipPath>\n            </defs>\n            <use xlink:href="#WITCHONE-CLASSNAME" clip-path="url(#cp-CLASSNAME)" />\n\t\t\t\t\t</svg>',
              ratio  : 0,
              witch  : 0,
              src    : '',
              link   : '',
              d__src : 'src__TLO',
              d__link: 'link__TLO',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '59.2%',
                  top   : '240px',
                  width : '40%',
                  height: '27px',
                },
              },
              inner: {
                class        : '.inner',
                css          : {
                  fill     : 'rgba(255,190,199,0.58)',
                  transform: 'skew(0deg,0deg) rotateX(0deg) rotateY(180deg) rotateZ(175deg)',
                  boxShadow: '-1px -9px 15px 1px rgba(166,163,163,0.5)',
                },
                hoverCss     : {},
                groupHoverCss: {},
              },
            },
            className: 'TLO',
            moduleCss: '3',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-xz',
            cName    : '形状',
            lock     : {},
            static   : {
              svg    : '<svg viewBox="9.039993286132812 19.052000045776367 186 103" preserveAspectRatio="ASPECTRATIO">\n            <defs>\n              <image id="img-CLASSNAME" xlink:href="SRC" preserveAspectRatio="xMidYMid slice" x="9.039993286132812" y="19.052000045776367" width="100%" height="100%"/>\n              <path id="path-CLASSNAME" preserveAspectRatio="xMidYMid slice" d="M195.04 19.052v103h-186v-103h186z"></path>\n              <clipPath id="cp-CLASSNAME">\n                <use xlink:href="#path-CLASSNAME"/>\n              </clipPath>\n            </defs>\n            <use xlink:href="#WITCHONE-CLASSNAME" clip-path="url(#cp-CLASSNAME)" />\n\t\t\t\t\t</svg>',
              ratio  : 0,
              witch  : 0,
              src    : '',
              link   : '',
              d__src : 'src__9QF',
              d__link: 'link__9QF',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '0px',
                  width : '100%',
                  height: '100%',
                },
              },
              inner: {
                class        : '.inner',
                css          : {
                  fill: 'rgba(255,255,255,1)',
                },
                hoverCss     : {},
                groupHoverCss: {},
              },
            },
            className: '9QF',
            moduleCss: '3',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '公司地址',
              link   : '',
              icon   : '',
              d__text: 'text__Sha',
              d__link: 'link__Sha',
              d__icon: 'icon__Sha',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '65px',
                  width : '100%',
                  height: '39px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color     : 'rgba(73,73,73,1)',
                  transition: 'all 0.2s 0s ease',
                  fontSize  : '16px',
                  fontFamily: '黑体',
                  fontWeight: 'bold',
                },
              },
            },
            lock     : {},
            className: 'Sha',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '请输入要描述的内容进行内容补充',
              link   : '',
              icon   : '',
              d__text: 'text__AAZ',
              d__link: 'link__AAZ',
              d__icon: 'icon__AAZ',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : '0px',
                  top   : '121px',
                  width : '100%',
                  height: '35px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color     : 'rgba(73,73,73,1)',
                  transition: 'all 0.2s 0s ease',
                  fontSize  : '14px',
                  fontFamily: '微软雅黑',
                  fontWeight: 'normal',
                },
              },
            },
            lock     : {},
            className: 'AAZ',
            moduleCss: '1',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : 'Address',
              link   : '',
              icon   : '',
              d__text: 'text__17k',
              d__link: 'link__17k',
              d__icon: 'icon__17k',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : 'calc(50% - 54px)',
                  top   : '183px',
                  width : '107px',
                  height: '37px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  color          : 'rgba(255,255,255,1)',
                  backgroundColor: 'rgba(255,184,42,1)',
                  fontSize       : '15px',
                },
              },
            },
            lock     : {},
            className: '17k',
            moduleCss: '2',
            sequence : 0,
          },
        },
        {
          info: {
            name     : 'module-an',
            cName    : '按钮',
            static   : {
              text   : '',
              link   : '',
              icon   : 'icl-bell-fill',
              d__text: 'text__eX1',
              d__link: 'link__eX1',
              d__icon: 'icon__eX1',
              order  : 0,
              script : '',
            },
            cssObj   : {
              self : {
                class: '',
                css  : {
                  left  : 'calc(50% - 45px)',
                  top   : '-45px',
                  width : '90px',
                  height: '90px',
                },
              },
              inner: {
                class        : '.inner',
                hoverCss     : {},
                groupHoverCss: {},
                css          : {
                  fontSize    : '32px',
                  color       : 'rgba(255,255,255,1)',
                  borderRadius: '100px',
                  transition  : 'all 0.2s 0s ease',
                  border      : '1px dashed rgba(255,184,44,1)',
                  boxShadow   : '0px 0px 0px 10px rgba(255,255,255,1), inset 0px 0px 0px 4px rgba(255,255,255,1), inset 0px 0px 0px 11px rgba(254,198,85,1), inset 0px 0px 0px 100px rgba(255,184,42,1)',
                },
              },
            },
            lock     : {},
            className: 'eX1',
            moduleCss: '17',
            sequence : 0,
          },
        },
      ],
    },
  ],
  tab     : [],
}
